import { Dispatch } from 'react';
import type { TokenId } from '@/utils/types';
import Token from '@/views/about/Token';

type Props = {
  setTokenId: Dispatch<TokenId>;
};

export default function Tokens({ setTokenId }: Props) {
  return (
    <div className="flex flex-col md:w-1/2 relative px-8">
      <h2 className="text-green font-bold text-center py-4 my-10 text-5xl">
        Tokens
      </h2>
      <div className="text-center">
        <Token
          srcKey="base_common"
          title="Base Common"
          description="The most common manny, completely unmarked."
          total={1144}
          onClick={() => setTokenId(405)}
        />
        <Token
          srcKey="base"
          title="Base Rare"
          description="Same as a base common, but serial numbered to 404."
          total={268}
          onClick={() => setTokenId(1)}
        />
        <Token
          srcKey="albino"
          title="Albino"
          description="One of the rarer Mannys, inspired by albino animals."
          total={24}
          onClick={() => setTokenId(401)}
        />
        <Token
          srcKey="holo"
          title="Holo"
          description="One of the rarer Mannys, a nod to holographic trading cards."
          total={24}
          onClick={() => setTokenId(42)}
        />
        <Token
          srcKey="inverted"
          title="Inverted"
          description="One of the rarest Mannys, inspired by hitting ctrl+i in photoshop."
          total={16}
          onClick={() => setTokenId(144)}
        />
        <Token
          srcKey="silver"
          title="Silver"
          description="One of the rarest Mannys, representing Manny's silver collection."
          total={16}
          onClick={() => setTokenId(66)}
        />
        <Token
          srcKey="stone"
          title="Stone"
          description="One of the rarest Mannys, inspired by Manny's art school sculpture days."
          total={16}
          onClick={() => setTokenId(244)}
        />
        <Token
          srcKey="zombie"
          title="Zombie"
          description="The second most rare Manny is an homage to cryptopunks."
          total={5}
          onClick={() => setTokenId(255)}
        />
        <Token
          srcKey="gold"
          title="Gold"
          description="The holy grail of mannys.game, created by calling mintGoldManny()."
          total={1}
          onClick={() => setTokenId(404)}
        />
        <Token
          srcKey="blitmap"
          title="Blitmap"
          description="A rare manny using cc0 artwork from the Blitmap universe."
          total={16}
          onClick={() => setTokenId(211)}
        />
        <Token
          srcKey="burnt"
          title="Burnt"
          description="A rare manny that's been burnt by one too many crypto scams."
          total={16}
          onClick={() => setTokenId(147)}
        />
        <Token
          srcKey="ecofriendly"
          title="Eco-Friendly"
          description="A rare manny celebrating nature, not backed by carbon offsets."
          total={16}
          onClick={() => setTokenId(1494)}
        />
        <Token
          srcKey="mannydenza"
          title="Mannydenza"
          description="A rare manny generated by one of the most versatile algorithms to date."
          total={16}
          onClick={() => setTokenId(983)}
        />
        <Token
          srcKey="rightclicked"
          title="Right-Clicked"
          description="A rare manny that's been right clicked and saved by too many NFT haters."
          total={16}
          onClick={() => setTokenId(910)}
        />
        <Token
          srcKey="rugged"
          title="Rugged"
          description="A rare manny that's draped in the artwork from rugstore.exchange."
          total={16}
          onClick={() => setTokenId(299)}
        />
        <Token
          srcKey="matrix"
          title="Matrix"
          description="A legendary manny that took the red pill."
          total={1}
          onClick={() => setTokenId(355)}
        />
        <Token
          srcKey="skulltrooper"
          title="Skull Trooper"
          description="A legendary manny that started playing in season one."
          total={1}
          onClick={() => setTokenId(398)}
        />
        <Token
          srcKey="pixelated"
          title="Pixelated"
          description="A legendary manny rendered as pixel art by artist Mykola Dosenko."
          total={1}
          onClick={() => setTokenId(903)}
        />
        <Token
          srcKey="poorlydrawn"
          title="Poorly Drawn"
          description="A legendary manny hand drawn (poorly) by the artist himself."
          total={1}
          onClick={() => setTokenId(1248)}
        />
        <Token
          srcKey="drmannyhattan"
          title="Dr. Mannyhattan"
          description="A legendary manny who's tired of Earth."
          total={1}
          onClick={() => setTokenId(1351)}
        />
        <Token
          srcKey="ditto"
          title="Ditto"
          description="A legendary manny that can reconstitute its entire cellular structure."
          total={1}
          onClick={() => setTokenId(1429)}
        />
        <Token
          srcKey="galaxy"
          title="Galaxy"
          description="A legendary manny as imagined by Mika."
          total={1}
          onClick={() => setTokenId(484)}
        />
        <Token
          srcKey="captainmannypants"
          title="Cpt. Mannypants"
          description="A legendary manny as imagined by Neoboy."
          total={1}
          onClick={() => setTokenId(560)}
        />
        <Token
          srcKey="mystery"
          title="???"
          description="Win new legendary mannys from discord giveaways"
          total={1}
          onClick={() => setTokenId(560)}
        />
      </div>
    </div>
  );
}
