import mannyTokens from 'fixtures/tokens';
import allAchievements from 'fixtures/achievements';
import { MANNY_TEXTURE_DEFAULT } from 'constants';

export const skinMap = {
  Zombie: {
    tokens: [13, 143, 180, 255, 363],
    description: 'The second most rare Manny is an homage to cryptopunks.',
    emoji: 'zombie',
  },
  Inverted: {
    tokens: [
      10, 17, 44, 60, 64, 77, 78, 144, 155, 165, 168, 216, 219, 298, 329, 397,
    ],
    description: 'A rare Manny created with ctrl+i in photoshop.',
    emoji: 'inverted',
  },
  Silver: {
    tokens: [
      7, 24, 66, 76, 85, 127, 148, 167, 172, 186, 210, 287, 303, 304, 348, 396,
    ],
    description: "A rare Manny paying tribute to Manny's silver collection.",
    emoji: 'silver',
  },
  Stone: {
    tokens: [
      11, 33, 36, 58, 108, 138, 171, 173, 184, 190, 209, 231, 234, 244, 308,
      332,
    ],
    description: 'A rare Manny evoking materiality and sculpture.',
    emoji: 'stone',
  },
  Albino: {
    tokens: [
      59, 91, 93, 94, 115, 118, 119, 141, 145, 150, 160, 179, 192, 195, 235,
      237, 271, 273, 291, 297, 325, 326, 381, 401,
    ],
    description: 'A rare Manny in the style of an albino animal.',
    emoji: 'albino',
  },
  Holo: {
    tokens: [
      42, 90, 92, 98, 122, 124, 132, 156, 162, 182, 197, 206, 240, 242, 253,
      306, 335, 341, 351, 382, 387, 390, 391, 399,
    ],
    description: 'A rare Manny inspired by holographic trading cards.',
    emoji: 'holo',
  },
  Gold: {
    tokens: [404],
    description: 'The holy grail of mannys.game.',
    emoji: 'gold',
  },
  'Base Rare': {
    description: 'Entry-level rare Manny.',
    tokens: [],
    emoji: 'baserare',
  },
  Blitmap: {
    tokens: [
      23, 47, 125, 128, 211, 257, 340, 1606, 1596, 1474, 976, 809, 544, 1085,
      1465, 646,
    ],
    description: 'A rare manny using cc0 artwork from the Blitmap universe.',
    se: true,
    emoji: 'blitmap',
  },
  Burnt: {
    tokens: [
      2, 147, 254, 265, 349, 357, 728, 637, 1315, 906, 1364, 1571, 751, 1332,
      1413, 1228,
    ],
    description: "A rare manny that's been burnt by one too many crypto scams.",
    se: true,
    emoji: 'burnt',
  },
  'Eco-Friendly': {
    tokens: [
      123, 199, 212, 217, 232, 284, 389, 1573, 718, 1494, 1565, 490, 1199, 1331,
      1318, 1156,
    ],
    description:
      'A rare manny celebrating nature, not backed by carbon offsets.',
    se: true,
    emoji: 'ecofriendly',
  },
  Mannydenza: {
    tokens: [
      50, 252, 34, 247, 665, 983, 1010, 1036, 1292, 1030, 831, 1361, 550, 748,
      780, 1152,
    ],
    description:
      'A rare manny with patterns generated by one of the most versatile algorithms to date.',
    se: true,
    emoji: 'mannydenza',
  },
  'Right-Clicked': {
    tokens: [
      142, 187, 241, 281, 899, 910, 1563, 1145, 577, 1390, 966, 1300, 1247,
      1174, 1056, 1484,
    ],
    description:
      "A rare manny that's been right clicked and saved by too many NFT haters.",
    se: true,
    emoji: 'rightclicked',
  },
  Rugged: {
    tokens: [
      126, 185, 248, 299, 999, 1139, 626, 1161, 1398, 1378, 711, 1528, 1444,
      1447, 1197, 437,
    ],
    description:
      "A rare manny that's draped in the artwork of the finest pixel rug from rugstore.exchange.",
    se: true,
    emoji: 'rugged',
  },
  Matrix: {
    tokens: [355],
    description: 'A legendary manny that took the red pill.',
    se: true,
    emoji: 'matrix',
  },
  'Skull Trooper': {
    tokens: [398],
    description: 'A legendary manny that started playing in season one.',
    se: true,
    emoji: 'skulltrooper',
  },
  Pixelated: {
    tokens: [903],
    description:
      'A legendary manny rendered as pixel art by artist Mykola Dosenko.',
    se: true,
    emoji: 'pixelated',
  },
  'Poorly Drawn': {
    tokens: [1248],
    description: 'A legendary manny hand drawn (poorly) by the artist himself.',
    se: true,
    emoji: 'poorlydrawn',
  },
  'Dr. Mannyhattan': {
    tokens: [1351],
    description: "A legendary manny who's tired of Earth.",
    se: true,
    emoji: 'drmannyhattan',
  },
  Ditto: {
    tokens: [1429],
    description:
      'A legendary manny that can reconstitute its entire cellular structure into what it sees.',
    se: true,
    emoji: 'ditto',
  },
  Galaxy: {
    tokens: [484],
    description: 'A legendary manny created by Mika.',
    se: true,
    emoji: 'galaxy',
  },
  'Captain Mannypants': {
    tokens: [560],
    description: 'A legendary manny created by Neoboy.',
    se: true,
    emoji: 'captainmannypants',
  },
};

const pointsMap = {
  100: [404],
  50: [],
  10: skinMap['Zombie'].tokens,
  7: [
    ...skinMap['Inverted'].tokens,
    ...skinMap['Silver'].tokens,
    ...skinMap['Stone'].tokens,
  ],
  5: [...skinMap['Albino'].tokens, ...skinMap['Holo'].tokens],
  3: [],
  1: [],
};

Object.keys(skinMap).forEach((skin) => {
  if (skinMap[skin].se) {
    const points = skinMap[skin].tokens.length === 1 ? '50' : '7';
    pointsMap[points].push(...skinMap[skin].tokens);
  }
});

for (let i = 1; i <= 1616; i++) {
  let isSpecialEdition = false;
  Object.keys(skinMap).forEach((skin) => {
    const skinMatch = skinMap[skin].tokens.some((tokenId) => tokenId === i);
    if (skinMatch && skinMap[skin].se) {
      isSpecialEdition = true;
    }
  });

  if (i >= 405 && !isSpecialEdition) {
    pointsMap['1'].push(i);
  } else {
    const isBase = Object.keys(skinMap).every((skin) =>
      skinMap[skin].tokens.every((tokenId) => tokenId !== i)
    );

    if (isBase) {
      pointsMap['3'].push(i);
    }
  }
}

const now = Date.now();

export const parseToken = (props) => {
  // support passing token id directly or props object where id lives in URL
  const initialId = Number.isInteger(props)
    ? props
    : props?.match?.params?.tokenId;
  const parsedTokenId = parseInt(initialId, 10);
  const isErrored =
    Number.isNaN(parsedTokenId) || parsedTokenId === 0 || parsedTokenId > 1616;
  if (isErrored) {
    return {};
  }

  const tokenMatch = mannyTokens.find(
    (mt) => String(mt.token_id) === String(parsedTokenId)
  );

  const cacheBust = (url) => url + `?ts=${now}`;

  const bonusAnim = tokenMatch?.attributes.find(
    (at) => at.trait_type === 'mood'
  );
  const bonusAnimName = bonusAnim?.value;

  return {
    tokenId: parsedTokenId,
    textureUrl: cacheBust(tokenMatch.texture_url || MANNY_TEXTURE_DEFAULT),
    bonusAnimName,
  };
};

export const asyncForEach = async (array, callback) => {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array);
  }
};

export const findRarestManny = (tokens) => {
  let bestManny = tokens[0];
  let bestPoints = 1;
  tokens.sort().forEach((tokenId) => {
    let pointsMatch = 0;
    Object.keys(pointsMap).forEach((pm) => {
      if (pointsMap[pm].some((_pmTokenId) => _pmTokenId === tokenId)) {
        pointsMatch = parseInt(pm, 10);
      }
    });
    if (pointsMatch > bestPoints) {
      bestManny = tokenId;
      bestPoints = pointsMatch;
    } else if (pointsMatch === bestPoints && tokenId < bestManny) {
      bestManny = tokenId;
      bestPoints = pointsMatch;
    }
  });

  return bestManny;
};

export const calculateAchievementPoints = (achievements) => {
  if (!achievements || !achievements.length) {
    return 0;
  }

  let totalPoints = 0;
  achievements.forEach((a) => {
    const aMatch = allAchievements.find((ach) => ach.id === a.achievement_id);
    totalPoints += aMatch.points;
  });

  return totalPoints;
};
